
server:
  port: 8762

spring:
  application:
    name: service-provider
  mvc:
    view:
      prefix: /
      suffix: .html

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      ### 服务分别向两个注册中心注册
      ### defaultZone: http://localhost:8771/eureka/ , http://localhost:8772/eureka/
      defaultZone: http://localhost:8761/eureka/
  ### 心跳检测检测与续约时间
  ### 测试时将值设置小些，保证服务关闭后注册中心能及时提出服务
  instance:
    ### Eureka 客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ### Eureka服务端在收到最后一次心跳后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照该规则）
    lease-expiration-duration-in-seconds: 2