
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    ### 是否注册自己到注册中心中去，这里本身就是注册中心，无需写true 但是集群啥的就要true，相互同步数据
    registerWithEureka: false
    ### 因为自己是注册中心，所以不要检索服务信息，但是集群啥的就要true，相互同步数据
    fetchRegistry: false

    serviceUrl:
      ### 注册中心与服务一般是一对多，但防止注册中心挂掉，可以再运行一个，两个互相注册，但是上面两个要改为true
      ### defaultZone: http://localhost:8772/eureka/ 注册到其他的注册中心去，不同注册中心用英文逗号分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    ### 测试时关闭自我保护机制，保证不可用服务及时挪出，分布式就不要关闭
    enable-self-preservation: false
    ### 剔除间隔
    eviction-interval-timer-in-ms: 2000

