server:
  port: 8003
spring:
  application:
    name: zk-Server-Provider
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
endpoints:
  restart:
    enabled: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
