
server:
  port: 8762

spring:
  application:
    name: service-provider

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/