
server:
  port: 8762

spring:
  application:
    name: service-provider

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      ### 服务分别向两个注册中心注册
      ### defaultZone: http://localhost:8771/eureka/ , http://localhost:8772/eureka/
      defaultZone: http://localhost:8761/eureka/