
server:
  port: 8766
spring:
  application:
    name: feign-consumer
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/