
server:
  port: 8765
spring:
  application:
    name: service-consumer
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/