###eureka 服务端口号
server:
  port: 8510
spring:
  application:
    name: consul-server-provider
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 192.168.18.221